BASIC ROUTINES=>
Creating arrays

In [13]:
import numpy as np

In [14]:
#using indices(dimensions, dtype=intp)indices (dimensions, dtype=intp) method 
np.indices((2,3))
np.array([[[0, 0, 0],[1, 1, 1]],[[0, 1, 2],[0, 1, 2]]])

array([[[0, 0, 0],
        [1, 1, 1]],

       [[0, 1, 2],
        [0, 1, 2]]])

In [15]:
#using fromfunction(function, dimensions, **kwargs) method
print(np.fromfunction(lambda i,j: i+j, (2,3)))

[[0. 1. 2.]
 [1. 2. 3.]]


In [16]:
#using lexsort (keys=, axis=-1) method
a = [1,2,1,3,1,5];b = [0,4,5,6,2,3]
ind = np.lexsort((b,a))
print (np.take(a,ind))
print("============")
print(np.take(b,ind))

[1 1 1 2 3 5]
[0 2 5 4 6 3]


Operation on two or more arrays

concatenate (seq=, axis=0)


Construct a new array from elements of the sequence object seq concatenated
along the given axis. The elements of the sequence object must have compatible types and be the same shape. If axis is None, then flatten each element
of seq before concatenating together to construct a 1-d array

In [17]:
#using outer(a, b) method
#compute an outerproduct which is syntactic sugar for a.ravel() [:,newaxis] *b.ravel() [newaxis,:] (after first converting a and b to ndarrays).
print(np.outer([1,2,3],[10,100,1000]))

[[  10  100 1000]
 [  20  200 2000]
 [  30  300 3000]]


Printing arrays

array2string (a)


The default printing mechanism uses this function to produce a string from an
array

set printoptions (precision=None, theshold=None, edgeitems=None,
linewidth=None, suppress=None)

Set options associated with representing an array.


precision the default number of digits of precision for floating point output
(default 8);
threshold total number of array elements which triggers printing only the
“ends” of the array rather than a full representation (default 1000);
edgeitems number of array elements in summary at beginning and end of
each dimension (default 3);
linewidth the number of characters per line (default 75);
suppress Boolean value indicating whether or not to suppress printing of
small floating point values using scientific notation (default False).

get printoptions()


Returns the values of precision, threshold, edgeitems, linewidth, and suppress
that control printing of arrays.


set string function (func, repr=1)


Set the function to use in response to str(array) or repr(array). By default this
function is array2string. The function passed in must take an array argument
and return a string. If func is None, then the print function is reset to a simple
internal function.

ADDITIONAL CONVENIENCE ROUTINES

In [18]:
#using kron(a, b) method to return a composite array with blocks from b scaled by elements of a
print(np.kron([1,10,100],[5,6,7]))
print("======================================")
print(np.kron([[1,10],[100,1000]],[[2,3],[4,5]]))


[  5   6   7  50  60  70 500 600 700]
[[   2    3   20   30]
 [   4    5   40   50]
 [ 200  300 2000 3000]
 [ 400  500 4000 5000]]


In [19]:
#usingh tile (a, reps) method
#Tile an N-dimensional array using the shape information in reps to create a larger N-dimensional array
np.tile([5,6,7],(1,2,3))

array([[[5, 6, 7, 5, 6, 7, 5, 6, 7],
        [5, 6, 7, 5, 6, 7, 5, 6, 7]]])

Basic functions

average (a, axis=None, weights=None, returned=0)


Computes the average along the indicated axis

cov (x, y=None, rowvar=1, bias=0)


Computes the covariance matrix of data in x.

corrcoef (x, y=None, rowvar=1, bias=0)


Estimate the correlation coefficient of x.

msort (a)


Return a new array, sorted along the first axis. Equivalent to b=a.copy();
b.sort(0)

median (m)


Returns the median of m along its first dimension.

histogram (x=, bins=None, range=None, normed=0)


Construct a histogram for the data in x (treated as one-dimensional array of type
float).

histogram2d (x, y, bins=10, range=None, normed=False)


Compute the two-dimensional histogram for a dataset (x,y) given the bins

histogramdd (sample, bins=10, range=None, normed=False)


Compute the D-dimensional histogram for a (vector) dataset contained in sample
give the bins.

logspace (start, stop, num=50, endpoint=True,base=10.0)


Evenly spaced samples on a logarithmic scale.

linspace (start, stop, num=50, endpoint=True, retstep=False):


Evenly spaced samples. Returns num evenly spaced samples from start to stop. If
endpoint is True, then the last sample is stop. If retstep is True, then return
the computed step size

In [20]:
#using meshgrid(x, y) method
# Returns num evenly spaced samples from start to stop. If endpoint is True, then the last sample is stop. If retstep is True, then return the computed step size
import numpy as np
X,Y =np.meshgrid([1,2,3], [4,5,6,7]);print(X); print(Y)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
[[4 4 4]
 [5 5 5]
 [6 6 6]
 [7 7 7]]


In [21]:
#using piecewise(x, condlist, funclist, *args, **kwargs) method to Compute a piecewise-defined function.
f1 = lambda x: x*x
x = np.r_[-4:6:20j]
y = np.piecewise(x,abs(x)<=3,[f1,0])+np.piecewise(x,x>=0,[1,0])
np.set_printoptions(precision=4); print(y)

[0.     0.     8.687  5.8615 3.59   1.8726 0.7091 0.0997 1.0443 1.5429
 2.5956 4.2022 6.3629 9.0776 1.     1.     1.     1.     1.     1.    ]


trim zeros (filt, trim=’fb’):


Trim the leading (’f’ in trim) and trailing (’b’ in trim) zeros from a sequence
according to the trim keyword

In [22]:
#using vectorize(pyfunc, otypes=None, doc=None)
#This creates a class whose instances have a call method that invokes a ufunc that has been dynamically built to call the python function pyfunc internally.
def myfunc(a,b):
    if(a>b): return a
    else: return b-1
vecfunc = np.vectorize(myfunc)
vecfunc([[1,2,3],[5,6,9]],[7,4,5])

array([[6, 3, 4],
       [6, 6, 9]])

POLYNOIMIAL FUNCTIONS

poly1d (c or r, r=0)


.r roots of the polynomial

.o order of the polynomial

.c polynomial coefficients as an array (also array () )

__call__(x) evaluate the polynomial at x (can be an array)

__getitem__(x) p[k] returns the coefficient on the kth power of x (backwards
from indexing the coefficient array)

In [23]:
#using poly1d (c or r, r=0)
#This construction returns an instance of a simple polynomial class
p=np.poly1d([2,5,7])
print(p)

   2
2 x + 5 x + 7


polyint (poly, m=1, k=None)

Return an exact mth-order integral of the polynomial represented in poly


In [24]:
print(np.polyint([1,3,4],m=2,k=[5,3]))

[0.0833 0.5    2.     5.     3.    ]


polyder (poly, m)

Return an exact mth-order derivative of the polynomial represented in poly. Also
available as .deriv(m=1) method of poly1d objects.

In [25]:
np.polyder([1,2,4,3])

array([3, 4, 4])

polyadd (p1, p2)

Add the two polynomials represented by coefficients: p1 (x) + p2 (x)

polysub (p1, p2)

Return coefficients for the polynomial found by subtracting the two polynomials
represented by p1 and p2: p1 (x) − p2 (x)

polymul (p1, p2)

Return the coefficients for p1 (x) p2 (x)


polydiv (p1, p2)

Return the quotient, q (x), and remainder, r (x), so that p1 (x) = q (x) p2 (x) +
r (x), with the order of r (x) less than the order of p2 (x)

polyval (p, y)

Evaluate the polynomial p at y.

polyfit (x,y,N)

Compute a best-fit polynomial in x of order N,