NUMPY ESSENTIALS

In [95]:
pip install numpy

In [96]:
import numpy
print (numpy.__version__)

1.23.4


In [97]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
a.shape
#indexing numpy arrays
print(a[1,1])

5


DATA-TYPE DESCRIPTORS

In [98]:
a =np.arange(60).reshape(3,4,5); 
print (a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]


Universal functions for arrays

In [99]:
a = np.arange(6, 10); 
print (a)
b = np.arange(12, 17);
table = a[:,np.newaxis] * b
print(table)

[6 7 8 9]
[[ 72  78  84  90  96]
 [ 84  91  98 105 112]
 [ 96 104 112 120 128]
 [108 117 126 135 144]]


ndarray Methods

In [100]:
#array conversion using tolist() method
a =np.array([[1,2,3],[4,5,6]]);
print(a.tolist())

[[1, 2, 3], [4, 5, 6]]


In [101]:
#using item(*args) method
a =np.array([[1,2,3],[4,5,6]]);
asc = a[0,0].item()
type(asc)

int

In [102]:
#using tofile(file=,sep="",format="")
a.tofile(file="myfile.txt",sep=":",format="%03d")
print(a)


[[1 2 3]
 [4 5 6]]


In [103]:
#using the view() method
print(a.view())

[[1 2 3]
 [4 5 6]]


In [104]:
#using the getfield(dtypoe="",offset=0)
a = np.array(["Hello","World","NumPy"])
a.getfield("S2",1)


array([b'', b'', b''], dtype='|S2')

In [105]:
a = np.arange(40).reshape((2,4,5))
b = a.transpose(2,0,1)
print(a.shape)
print(b.shape)

print(a.strides)
print(b.strides)
print("This is A")
print(a)

print("This is B")
print(b)

(2, 4, 5)
(5, 2, 4)
(80, 20, 4)
(4, 80, 20)
This is A
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]]
This is B
[[[ 0  5 10 15]
  [20 25 30 35]]

 [[ 1  6 11 16]
  [21 26 31 36]]

 [[ 2  7 12 17]
  [22 27 32 37]]

 [[ 3  8 13 18]
  [23 28 33 38]]

 [[ 4  9 14 19]
  [24 29 34 39]]]


Array item selection and manipulation

In [106]:
#using choose(choices, out=None, mode="raise") method
a = np.array([0,3,2,1])
a.choose([0,1,2,3],[10,11,12,13],[20,21,22,23],[30,31,32,33])

array([ 0, 31, 22, 13])

In [107]:
#using sort (axis=-1, kind="quick", order=None) method
a=np.array([[0.2,1.3,2.5],[1.5,0.1,1.4]]);
b=a.copy();
b.sort(0); 
print (b)
print("================")
b=a.copy(); 
b.sort(1);
print(b)

[[0.2 0.1 1.4]
 [1.5 1.3 2.5]]
[[0.2 1.3 2.5]
 [0.1 1.4 1.5]]


In [108]:
#using argsort(axis=-1, kind="quick", order=None) method
a=np.array([[0.2,1.3,2.5],[1.5,0.1,1.4]]);
b=a.copy();
print(b.argsort(0))


[[0 1 1]
 [1 0 0]]


In [109]:
#using searchsorted(values, side="left") method
b=a.ravel(); b.sort()
b.searchsorted([0.0, 1.35, 2.0, 3.0])

array([0, 3, 5, 6], dtype=int64)

In [110]:
#using nonzero () method
x =np.arange(15);
y=x.reshape(3,5)
(x>8).nonzero()
(y>8).nonzero()

(array([1, 2, 2, 2, 2, 2], dtype=int64),
 array([4, 0, 1, 2, 3, 4], dtype=int64))

In [111]:
#using the compress (condition=, axis=None, out=None) method
x=np.array([0,1,2,3])
print(x.compress(x > 2))

[3]


In [112]:
#using the diagonal (offset=0, axis1=0, axis2=1) method
a=np.arange(25).reshape(5,5);
print(a)
print("\n")
print("a.diagonal()")
print(a.diagonal())
print("\n")
print("a.diagonal(1)")
print(a.diagonal(1))
print("\n")
print("a.diagonal(-1)")
print (a.diagonal(-1))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


a.diagonal()
[ 0  6 12 18 24]


a.diagonal(1)
[ 1  7 13 19]


a.diagonal(-1)
[ 5 11 17 23]
